### ISSUE TITLE
Please port this amazing theme to Jupyter Lab >= 2.0.0

### ISSUE THREAD

**Issue by davzzar** [karosc/jupyterlab_dracula#3]
I would love to use this theme but the current version is not compatible with Jupyter Lab version 2.0.0 and above. Any way this can be updated? Or some guidance on how to port it ourselves?

**Comment by laugh12321** [comment]
me too, Please port this amazing theme to Jupyter Lab >= 2.0.1

**Comment by cfriedline** [comment]
I have a working fork here https://github.com/cfriedline/jupyterlab_dracula/tree/jupyterlab-2, but not sure if this is what should be done. I'm definitely not a javascript developer, either. There is also this repo, which seems to mirror this one to some extent: https://github.com/dracula/jupyterlab. Perhaps that one is the better place for these changes, @karosc?

**Comment by karosc** [comment]
Firstly, so happy to hear people are using this.

I have not moved to jupyterlab 2 yet, so I have not ported this. I need to put some work into it to get things moving. I know jupyterlab provides some [migration guidance on their site](https://jupyterlab.readthedocs.io/en/stable/developer/extension_migration.html).

As for which repo is the official, the one over at https://github.com/dracula/jupyterlab is official. This one is dated and I should get around to erasing it.

When I get things updated on npm, I'll close this issue.

**Comment by cfriedline** [comment]
Thanks, @karosc!

**Comment by karosc** [comment]
Alright, I updated it according to the [theme cookiecutter](https://github.com/jupyterlab/theme-cookiecutter). 

`jupyter labextension install @karosc/jupyterlab_dracula` should get you the [most up to date version](https://www.npmjs.com/package/@karosc/jupyterlab_dracula)
